#!/usr/bin/env bash

gen () {
    local TAG=kotify/`echo $1 | sed 's/-/:/'`
    local NAME=`echo $1 | sed 's/[^a-zA-Z0-9]/_/g'`
    echo "build.$NAME": >> Makefile
    echo "	docker build -f $1/Dockerfile . --tag=$TAG" >> Makefile
    echo "push.$NAME": >> Makefile
    echo "	docker push $TAG" >> Makefile
    echo "publish.$NAME: build.$NAME push.$NAME" >> Makefile
    echo '' >> Makefile
    echo '' >> Makefile
}

cat << EOF > Makefile
# DO NOT EDIT, AUTOGENERATED BY gen.sh

all: refresh-base-images publish.all

refresh-base-images:
	grep 'FROM' **/Dockerfile | cut -d ' ' -f 2 | xargs -L 1 docker pull


EOF

for f in `ls | grep -`; do gen $f; done

echo -n 'publish.all:' >> Makefile

for f in `ls | grep -`; do
    NAME=`echo $f | sed 's/[^a-zA-Z0-9]/_/g'`
    echo -n " publish.$NAME" >> Makefile;
done

echo '' >> Makefile
