# DO NOT EDIT, AUTOGENERATED BY gen.sh

all: refresh-base-images publish.all

refresh-base-images:
	grep 'FROM' **/Dockerfile | cut -d ' ' -f 2 | xargs -L 1 docker pull


build.circleci_python37_node10_aws:
	docker build -f circleci-python37-node10-aws/Dockerfile . --tag=kotify/circleci:python37-node10-aws
push.circleci_python37_node10_aws:
	docker push kotify/circleci:python37-node10-aws
publish.circleci_python37_node10_aws: build.circleci_python37_node10_aws push.circleci_python37_node10_aws


build.circleci_python37_node10_browsers_aws:
	docker build -f circleci-python37-node10-browsers-aws/Dockerfile . --tag=kotify/circleci:python37-node10-browsers-aws
push.circleci_python37_node10_browsers_aws:
	docker push kotify/circleci:python37-node10-browsers-aws
publish.circleci_python37_node10_browsers_aws: build.circleci_python37_node10_browsers_aws push.circleci_python37_node10_browsers_aws


build.postgres_non_durable:
	docker build -f postgres-non-durable/Dockerfile . --tag=kotify/postgres:non-durable
push.postgres_non_durable:
	docker push kotify/postgres:non-durable
publish.postgres_non_durable: build.postgres_non_durable push.postgres_non_durable


build.python_2_7_node_browsers:
	docker build -f python-2.7-node-browsers/Dockerfile . --tag=kotify/python:2.7-node-browsers
push.python_2_7_node_browsers:
	docker push kotify/python:2.7-node-browsers
publish.python_2_7_node_browsers: build.python_2_7_node_browsers push.python_2_7_node_browsers


publish.all: publish.circleci_python37_node10_aws publish.circleci_python37_node10_browsers_aws publish.postgres_non_durable publish.python_2_7_node_browsers
