version: "3.7"

services:
  weasyprint:
    build: .
    container_name: weasyprint
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=development
    command: flask run --host 0.0.0.0 --port 8139
    volumes:
      - ./:/opt/
    ports:
      - "8139:8139"
