name: PostgreSQL Images

on:
  push:
    branches:
      - master
    paths:
      - "postgres/**"
  pull_request:
    paths:
      - "postgres/**"

concurrency:
  group: ${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  # https://github.com/marketplace/actions/build-and-push-docker-images
  postgres:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 11, 12, 13, 14]
        extension: [non-durable, non-durable-anon]
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: "${{ github.ref == 'refs/heads/master' }}"
          tags: kotify/postgres:${{ matrix.version }}-${{ matrix.extension }}
          file: ./postgres/Dockerfile.${{ matrix.extension }}
          context: ./postgres
          build-args: |
            POSTGRES_VERSION=${{ matrix.version }}
