name: PostgreSQL Images

on:
  push:
    branches:
      - master
    paths:
      - "postgres/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "postgres/**"
      - ".github/workflows/**"
  schedule:
    - cron: "06 09 * * 1"

concurrency:
  group: ${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  # https://github.com/marketplace/actions/build-and-push-docker-images
  postgres:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        version: [12, 13, 14, 15, 16, 17]
        extension: [non-durable, non-durable-anon]
      fail-fast: "${{ github.ref != 'refs/heads/master' }}"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: "${{ github.ref == 'refs/heads/master' }}"
          tags: |
            ghcr.io/kotify/postgres:${{ matrix.version }}-${{ matrix.extension }}
          file: ./postgres/Dockerfile.${{ matrix.extension }}
          context: ./postgres
          build-args: |
            POSTGRES_VERSION=${{ matrix.version }}
          platforms: |
            linux/amd64
            linux/arm64
